[package]
name = "migr82gitea"
version = "0.1.0"
authors = ["Amritanshu Pandey <amp.msit@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
